# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Serverless Cron Job CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{  runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          pip install --upgrade pip pre-commit poetry
          npm install -g aws-cdk
          make deps
          pip install -r dev_requirements.txt
          pip install -r lambda_requirements.txt
      - name: pre commit
        run: |
          make pre-commit
      - name: Lint with mypy
        run: |
          make lint
      - name: file format
        run: |
          make format
      - name: Complexity scan
        run: |
          make complex
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Unit tests
        run: |
          make unit
